### PR TITLE
Updating info on Sean Kelly, preventing speaker from appearing twice …

### PR DESCRIPTION
**Pull request by StabbyCutyou**
…in speakers list

Fixing the spelling of my name.

Also, I show up twice on the speakers page, which seems like the wrong thing to do. I made an attempt at blocking the 2nd one with a new field but the instructions on running the site didn't work for me (wondering if it needs to be specific version of node?) so it's more of an inspirational attempt rather than something you'd want to just accept as-is.

Unless it works.

### CODE REVIEW

**Comment by StabbyCutyou** [comment]
Speakers page looks down?

https://www.golanguk.com/speakers/#

Might be the change I proposed here - like I said, I wasn't able to follow
the instructions and get the code running so, likely there was an error in
my update to the template.

**Comment by johannac** [comment]
@StabbyCutyou should be fixed now :) That's my fault, I didn't test your change either before merging :P 

8054 image_thumb_35c6e986

**Comment by StabbyCutyou** [comment]
Hahaha cool.

Sorry about that! I hate submitting untested stuff :/

**Comment by johannac** [comment]
Yeah sorry about that, that was our fault! I think I've fixed the npm stuff now.

**Pull request merged**
