### PR TITLE
Change years of copyright

### PR DESCRIPTION
**Pull request by agonzalezro**
I would prefer a: Attribution-NonCommercial CC BY-NC

More info: https://creativecommons.org/licenses/

Can we discuss this?

### CODE REVIEW

**Comment by samdb** [comment]
I don't actually think we need any restrictions at all.

**Comment by agonzalezro** [comment]
So, `CC BY`or let it as it is?

**Comment by samdb** [comment]
CC BY is good

**Comment by agonzalezro** [comment]
We have decided for CC-BY license as shown on the PR. LGTM now

**Pull request merged**
